# Configuration for musl target
[target.x86_64-unknown-linux-musl.env]
passthrough = [
    "OPENSSL_STATIC",
    "OPENSSL_VENDOR",
]

# Configuration for ARM64 Linux
[target.aarch64-unknown-linux-gnu.env]
passthrough = [
    "OPENSSL_STATIC",
    "OPENSSL_VENDOR",
]

# Configuration for ARMv7
[target.armv7-unknown-linux-gnueabihf.env]
passthrough = [
    "OPENSSL_STATIC",
    "OPENSSL_VENDOR",
]
