# Use sccache's proven Docker images
[target.x86_64-unknown-linux-musl]
image = "messense/rust-musl-cross:x86_64-musl"

[target.aarch64-unknown-linux-musl]
image = "messense/rust-musl-cross:aarch64-musl"

[target.armv7-unknown-linux-musleabihf]
image = "messense/rust-musl-cross:armv7-musleabihf"
