[build]
# Use pre-built Docker images for faster builds
pre-build = []

[target.aarch64-unknown-linux-gnu]
# Use the official cross Docker image with OpenSSL pre-installed
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:latest"

[target.aarch64-unknown-linux-gnu.env]
# Environment variables for the build
passthrough = [
    "OPENSSL_STATIC",
    "OPENSSL_DIR",
    "OPENSSL_LIB_DIR",
    "OPENSSL_INCLUDE_DIR",
]
# Force static linking of OpenSSL
OPENSSL_STATIC = "1"