# Configuration for musl target
[target.x86_64-unknown-linux-musl]
image = "ghcr.io/cross-rs/cross:x86_64-unknown-linux-musl-0.2.5"

[target.x86_64-unknown-linux-musl.env]
passthrough = [
    "OPENSSL_DIR",
    "OPENSSL_LIB_DIR",
    "OPENSSL_INCLUDE_DIR",
]

# Configuration for ARM64 Linux
[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/cross:aarch64-unknown-linux-gnu-0.2.5"

[target.aarch64-unknown-linux-gnu.env]
passthrough = [
    "OPENSSL_DIR",
    "OPENSSL_LIB_DIR", 
    "OPENSSL_INCLUDE_DIR",
]

# Configuration for ARMv7
[target.armv7-unknown-linux-gnueabihf]
image = "ghcr.io/cross-rs/cross:armv7-unknown-linux-gnueabihf-0.2.5"

[target.armv7-unknown-linux-gnueabihf.env]
passthrough = [
    "OPENSSL_DIR",
    "OPENSSL_LIB_DIR",
    "OPENSSL_INCLUDE_DIR",
]
