# Configuration for musl target
[target.x86_64-unknown-linux-musl]
# Use Alpine-based image for musl
image = "messense/rust-musl-cross:x86_64-musl"

[target.x86_64-unknown-linux-musl.env]
passthrough = [
    "OPENSSL_STATIC",
]

# Configuration for ARM64 Linux
[target.aarch64-unknown-linux-gnu.env]
passthrough = [
    "OPENSSL_STATIC",
]

# Configuration for ARMv7
[target.armv7-unknown-linux-gnueabihf.env]
passthrough = [
    "OPENSSL_STATIC",
]
