# Configuration for musl target
[target.x86_64-unknown-linux-musl]
# Use emk/rust-musl-builder which has OpenSSL pre-configured
image = "ekidd/rust-musl-builder"

[target.x86_64-unknown-linux-musl.env]
passthrough = [
    "OPENSSL_STATIC",
    "X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_STATIC",
]

# Configuration for ARM64 Linux
[target.aarch64-unknown-linux-gnu.env]
passthrough = [
    "OPENSSL_STATIC",
    "AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_STATIC",
]

# Configuration for ARMv7
[target.armv7-unknown-linux-gnueabihf.env]
passthrough = [
    "OPENSSL_STATIC",
    "ARMV7_UNKNOWN_LINUX_GNUEABIHF_OPENSSL_STATIC",
]
