# Use sccache's proven Docker images with pkg-config pre-build
[target.x86_64-unknown-linux-musl]
image = "messense/rust-musl-cross:x86_64-musl"
pre-build = ["apt-get update && apt-get install -y pkg-config libssl-dev"]

[target.aarch64-unknown-linux-musl]
image = "messense/rust-musl-cross:aarch64-musl"
pre-build = ["apt-get update && apt-get install -y pkg-config libssl-dev"]

[target.armv7-unknown-linux-gnueabihf]
image = "ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:edge"
pre-build = ["apt-get update && apt-get install -y pkg-config libssl-dev"]
