[package]
name = "ck-models"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
ck-core = { path = "../ck-core" }

anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }