title: ck Documentation
description: Semantic code search that understands what you're looking for
remote_theme: just-the-docs/just-the-docs

# Enable search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Aux links (top-right)
aux_links:
  "GitHub":
    - "https://github.com/BeaconBay/ck"
  "crates.io":
    - "https://crates.io/crates/ck-search"

# Footer
footer_content: "Copyright &copy; 2024 BeaconBay. Distributed under Apache-2.0 and MIT licenses."

# Color scheme
color_scheme: dark

# Code copy button
enable_copy_code_button: true
